name: norlund
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#787878'
    - '#3d3a33'
    - '#b3b5b4'
  brandStrength: 0.6091138774063438
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
