name: norlund
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06050b'
    - '#d3c9d1'
    - '#40475a'
    - '#646f83'
    - '#fffeff'
  brandStrength: 0.6091138774063438
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
